import { createAnimations } from '@tamagui/animations-react-native';
import { createFont, createTamagui, createTokens } from 'tamagui';

const tokens = createTokens({
  color: {
    transparent: 'transparent',
    lightBackground: '#F5F3EE',
    lightBackgroundSubtle: '#ECE9E2',
    lightSurface: '#FAF9F6',
    lightSurfaceElevated: '#FFFFFF',
    lightSurfacePressed: '#E4E0D7',
    lightTextPrimary: '#22231F',
    lightTextSecondary: '#65655E',
    lightTextMuted: '#929188',
    lightBorder: '#D9D5CC',
    lightAccent: '#566B5E',
    lightAccentSoft: '#DDE5DE',
    lightSuccess: '#4E745E',
    lightWarning: '#9B7045',
    lightDanger: '#9A5B52',
    darkBackground: '#161815',
    darkBackgroundSubtle: '#1D201C',
    darkSurface: '#20231F',
    darkSurfaceElevated: '#272B26',
    darkSurfacePressed: '#30352F',
    darkTextPrimary: '#F1F0EA',
    darkTextSecondary: '#B9BBB2',
    darkTextMuted: '#858A81',
    darkBorder: '#393E38',
    darkAccent: '#9EB5A5',
    darkAccentSoft: '#2D3931',
    darkSuccess: '#82AC90',
    darkWarning: '#C29A6C',
    darkDanger: '#C68479',
    lightOverlay: '#17181566',
    darkOverlay: '#00000099',
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    '2xl': 24,
    '3xl': 32,
    '4xl': 40,
    '5xl': 56,
    true: 16,
  },
  size: {
    xs: 12,
    sm: 16,
    md: 20,
    lg: 24,
    xl: 32,
    '2xl': 40,
    '3xl': 48,
    control: 48,
    icon: 40,
    scoreRing: 116,
    scoreRingInner: 102,
    progress: 6,
    ringStroke: 7,
    dot: 8,
    calendar: 40,
    true: 20,
  },
  radius: {
    xs: 4,
    sm: 7,
    md: 10,
    lg: 14,
    xl: 18,
    round: 999,
    true: 10,
  },
  zIndex: {
    base: 0,
    nav: 10,
    sheet: 100,
    true: 0,
  },
});

const bodyFont = createFont({
  family: 'System',
  size: {
    caption: 12,
    label: 13,
    body: 15,
    bodyStrong: 15,
    sectionTitle: 13,
    title: 20,
    headline: 30,
    display: 42,
    metric: 34,
    true: 15,
  },
  lineHeight: {
    caption: 17,
    label: 18,
    body: 22,
    bodyStrong: 22,
    sectionTitle: 18,
    title: 26,
    headline: 36,
    display: 48,
    metric: 40,
    true: 22,
  },
  weight: {
    regular: '400',
    medium: '500',
    semibold: '600',
    true: '400',
  },
  letterSpacing: {
    caption: 0.1,
    label: 0.4,
    body: 0,
    bodyStrong: 0,
    sectionTitle: 1.2,
    title: -0.2,
    headline: -0.8,
    display: -1.2,
    metric: -0.8,
    true: 0,
  },
});

const animations = createAnimations({
  fast: { type: 'timing', duration: 140 },
  medium: { type: 'spring', damping: 22, stiffness: 180, mass: 0.8 },
  slow: { type: 'spring', damping: 24, stiffness: 120, mass: 1 },
});

export const config = createTamagui({
  animations,
  tokens,
  fonts: { body: bodyFont, heading: bodyFont },
  themes: {
    light: {
      background: tokens.color.lightBackground,
      backgroundSubtle: tokens.color.lightBackgroundSubtle,
      surface: tokens.color.lightSurface,
      surfaceElevated: tokens.color.lightSurfaceElevated,
      surfacePressed: tokens.color.lightSurfacePressed,
      color: tokens.color.lightTextPrimary,
      textPrimary: tokens.color.lightTextPrimary,
      textSecondary: tokens.color.lightTextSecondary,
      textMuted: tokens.color.lightTextMuted,
      border: tokens.color.lightBorder,
      accent: tokens.color.lightAccent,
      accentSoft: tokens.color.lightAccentSoft,
      success: tokens.color.lightSuccess,
      warning: tokens.color.lightWarning,
      danger: tokens.color.lightDanger,
      overlay: tokens.color.lightOverlay,
    },
    dark: {
      background: tokens.color.darkBackground,
      backgroundSubtle: tokens.color.darkBackgroundSubtle,
      surface: tokens.color.darkSurface,
      surfaceElevated: tokens.color.darkSurfaceElevated,
      surfacePressed: tokens.color.darkSurfacePressed,
      color: tokens.color.darkTextPrimary,
      textPrimary: tokens.color.darkTextPrimary,
      textSecondary: tokens.color.darkTextSecondary,
      textMuted: tokens.color.darkTextMuted,
      border: tokens.color.darkBorder,
      accent: tokens.color.darkAccent,
      accentSoft: tokens.color.darkAccentSoft,
      success: tokens.color.darkSuccess,
      warning: tokens.color.darkWarning,
      danger: tokens.color.darkDanger,
      overlay: tokens.color.darkOverlay,
    },
  },
  shorthands: {
    bg: 'backgroundColor',
    br: 'borderRadius',
    bw: 'borderWidth',
    bc: 'borderColor',
    f: 'flex',
    fw: 'fontWeight',
    h: 'height',
    jc: 'justifyContent',
    ai: 'alignItems',
    m: 'margin',
    mb: 'marginBottom',
    mt: 'marginTop',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    p: 'padding',
    pb: 'paddingBottom',
    pt: 'paddingTop',
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    w: 'width',
  } as const,
});

export type AppConfig = typeof config;

declare module 'tamagui' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;
