import { createAnimations } from '@tamagui/animations-react-native';
import { createFont, createTamagui, createTokens } from 'tamagui';

const tokens = createTokens({
  color: {
    transparent: 'transparent',
    lightBackground: '#F6F9FD',
    lightBackgroundSubtle: '#EAF3FC',
    lightSurface: '#FFFFFF',
    lightSurfaceElevated: '#FFFFFF',
    lightSurfacePressed: '#DCEBFA',
    lightTextPrimary: '#10283E',
    lightTextSecondary: '#526C82',
    lightTextMuted: '#587289',
    lightBorder: '#D5E2EE',
    lightAccent: '#0868C9',
    lightAccentSoft: '#E4F1FE',
    lightAccentContrast: '#FFFFFF',
    lightSuccess: '#147F5F',
    lightSuccessContrast: '#FFFFFF',
    lightWarning: '#A65B00',
    lightDanger: '#C83F4D',
    darkBackground: '#071726',
    darkBackgroundSubtle: '#0A1C2D',
    darkSurface: '#0E2235',
    darkSurfaceElevated: '#15314A',
    darkSurfacePressed: '#1B3B57',
    darkTextPrimary: '#F3F8FC',
    darkTextSecondary: '#B8CBDA',
    darkTextMuted: '#9AB2C5',
    darkBorder: '#29465E',
    darkAccent: '#64B5FF',
    darkAccentSoft: '#123B5F',
    darkAccentContrast: '#071726',
    darkSuccess: '#58C6A0',
    darkSuccessContrast: '#071726',
    darkWarning: '#F2B45E',
    darkDanger: '#FF8791',
    lightOverlay: '#07172666',
    darkOverlay: '#00000099',
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    '2xl': 24,
    '3xl': 32,
    '4xl': 40,
    '5xl': 56,
    true: 16,
  },
  size: {
    xs: 12,
    sm: 16,
    md: 20,
    lg: 24,
    xl: 32,
    '2xl': 40,
    '3xl': 48,
    control: 52,
    icon: 44,
    scoreRing: 116,
    scoreRingInner: 102,
    progress: 6,
    ringStroke: 7,
    dot: 8,
    calendar: 40,
    true: 20,
  },
  radius: {
    xs: 4,
    sm: 7,
    md: 10,
    lg: 16,
    xl: 22,
    round: 999,
    true: 10,
  },
  zIndex: {
    base: 0,
    nav: 10,
    sheet: 100,
    true: 0,
  },
});

const bodyFont = createFont({
  family: 'System',
  size: {
    caption: 12,
    label: 13,
    body: 15,
    bodyStrong: 15,
    sectionTitle: 13,
    title: 20,
    headline: 30,
    display: 42,
    metric: 34,
    true: 15,
  },
  lineHeight: {
    caption: 17,
    label: 18,
    body: 22,
    bodyStrong: 22,
    sectionTitle: 18,
    title: 26,
    headline: 36,
    display: 48,
    metric: 40,
    true: 22,
  },
  weight: {
    regular: '400',
    medium: '500',
    semibold: '600',
    true: '400',
  },
  letterSpacing: {
    caption: 0.1,
    label: 0.4,
    body: 0,
    bodyStrong: 0,
    sectionTitle: 1.2,
    title: -0.2,
    headline: -0.8,
    display: -1.2,
    metric: -0.8,
    true: 0,
  },
});

const animations = createAnimations({
  fast: { type: 'timing', duration: 140 },
  medium: { type: 'spring', damping: 22, stiffness: 180, mass: 0.8 },
  slow: { type: 'spring', damping: 24, stiffness: 120, mass: 1 },
});

export const config = createTamagui({
  animations,
  tokens,
  fonts: { body: bodyFont, heading: bodyFont },
  themes: {
    light: {
      background: tokens.color.lightBackground,
      backgroundSubtle: tokens.color.lightBackgroundSubtle,
      surface: tokens.color.lightSurface,
      surfaceElevated: tokens.color.lightSurfaceElevated,
      surfacePressed: tokens.color.lightSurfacePressed,
      color: tokens.color.lightTextPrimary,
      textPrimary: tokens.color.lightTextPrimary,
      textSecondary: tokens.color.lightTextSecondary,
      textMuted: tokens.color.lightTextMuted,
      border: tokens.color.lightBorder,
      accent: tokens.color.lightAccent,
      accentSoft: tokens.color.lightAccentSoft,
      accentContrast: tokens.color.lightAccentContrast,
      success: tokens.color.lightSuccess,
      successContrast: tokens.color.lightSuccessContrast,
      warning: tokens.color.lightWarning,
      danger: tokens.color.lightDanger,
      overlay: tokens.color.lightOverlay,
    },
    dark: {
      background: tokens.color.darkBackground,
      backgroundSubtle: tokens.color.darkBackgroundSubtle,
      surface: tokens.color.darkSurface,
      surfaceElevated: tokens.color.darkSurfaceElevated,
      surfacePressed: tokens.color.darkSurfacePressed,
      color: tokens.color.darkTextPrimary,
      textPrimary: tokens.color.darkTextPrimary,
      textSecondary: tokens.color.darkTextSecondary,
      textMuted: tokens.color.darkTextMuted,
      border: tokens.color.darkBorder,
      accent: tokens.color.darkAccent,
      accentSoft: tokens.color.darkAccentSoft,
      accentContrast: tokens.color.darkAccentContrast,
      success: tokens.color.darkSuccess,
      successContrast: tokens.color.darkSuccessContrast,
      warning: tokens.color.darkWarning,
      danger: tokens.color.darkDanger,
      overlay: tokens.color.darkOverlay,
    },
  },
  media: {
    compact: { maxWidth: 379 },
    tablet: { minWidth: 768 },
    short: { maxHeight: 700 },
  },
  shorthands: {
    bg: 'backgroundColor',
    br: 'borderRadius',
    bw: 'borderWidth',
    bc: 'borderColor',
    f: 'flex',
    fw: 'fontWeight',
    h: 'height',
    jc: 'justifyContent',
    ai: 'alignItems',
    m: 'margin',
    mb: 'marginBottom',
    mt: 'marginTop',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    p: 'padding',
    pb: 'paddingBottom',
    pt: 'paddingTop',
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    w: 'width',
  } as const,
});

export type AppConfig = typeof config;

declare module 'tamagui' {
  // Module augmentation requires an interface so Tamagui can infer every custom token and theme key.
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;
